ISRPO_LR1.Web/Models/ErrorViewModel.cs
namespace ISRPO_LR1.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ISRPO_LR1.Web/Models/ViewModels/BaseIndexViewModel.cs
namespace ISRPO_LR1.Web.Models.ViewModels;

public class BaseIndexViewModel<T>
{
    public List<T> Items { get; set; }
}

ISRPO_LR1.Web/Models/ViewModels/GradeCreateViewModel.cs
using System.ComponentModel.DataAnnotations;
using ISRPO_LR1.Domain;

namespace ISRPO_LR1.Web.Models.ViewModels;

public class GradeCreateViewModel : Grade
{
    [Display(Name = "Предмет")] 
    public Subject g_sj { get; set; } = new Subject();
    [Display(Name = "Студент")] 
    public Student g_s { get; set; } = new Student();
    public List<Subject> Subjects { get; set; } = new List<Subject>();
    public List<Student> Students { get; set; } = new List<Student>();
}

ISRPO_LR1.Web/Controllers/Base/BaseController.cs
using ISRPO_LR1.Domain.Service;
using ISRPO_LR1.Web.Models.ViewModels;
using ISRPO_LR1.Web.Repositories.Base;
using Microsoft.AspNetCore.Mvc;

namespace ISRPO_LR1.Web.Controllers.Base;

public abstract class BaseController<T> : Controller
{
    protected readonly BaseRepository<T> BaseRepository;
    protected readonly ILogger<BaseController<T>> Logger;

    public BaseController(BaseRepository<T> baseRepository, ILogger<BaseController<T>> logger)
    {
        BaseRepository = baseRepository;
        Logger = logger;
    }
    
    public virtual async Task<IActionResult> Index()
    {
        var response = await BaseRepository.Get();
        if (!response.Success)
            return View(new ServiceResponseModel<BaseIndexViewModel<T>>()
            {
                Error = response.Error
            });
        return View(new ServiceResponseModel<BaseIndexViewModel<T>>()
        {
            Success = true,
            Item = new BaseIndexViewModel<T>()
            {
                Items = response.Item ?? new List<T>()
            }
        });
    }
    
    [HttpGet("get/{id:int}")]
    public virtual async Task<IActionResult> Get(int id)
    {
        var response = await BaseRepository.Get(id);
        return View(response);
    }
    
    [HttpGet("create")]
    public virtual async Task<IActionResult> Create()
    {
        return View();
    }
    
    [HttpPost("create")]
    public virtual async Task<IActionResult> Create(T model)
    {
        var response = await BaseRepository.Post(model);
        if (response.Success)
            return RedirectToAction("Index");
        return View();
    }
    
    [HttpGet("edit/{id:int}")]
    public virtual async Task<IActionResult> Edit(int id)
    {
        var response = await BaseRepository.Get(id);
        return View(response);
    }
    
    [HttpPost("edit/{id:int}")]
    public virtual async Task<IActionResult> Edit(int id, T model)
    {
        var response = await BaseRepository.Put(id, model);
        if (response.Success)
            return RedirectToAction("Index");
        return View();
    }
    
    [HttpGet("delete")]
    public virtual async Task<IActionResult> Delete(int id)
    {
        var response = await BaseRepository.Delete(id);
        if (response)
            return RedirectToAction("Index");
        return View("Get");
    }
}

ISRPO_LR1.Web/Controllers/GradesController.cs
using ISRPO_LR1.Domain;
using ISRPO_LR1.Domain.Service;
using ISRPO_LR1.Web.Controllers.Base;
using ISRPO_LR1.Web.Models.ViewModels;
using ISRPO_LR1.Web.Repositories;
using ISRPO_LR1.Web.Repositories.Base;
using Microsoft.AspNetCore.Mvc;

namespace ISRPO_LR1.Web.Controllers;

[Route("grades")]
public class GradesController : BaseController<Grade>
{
    private readonly StudentsRepository _studentsRepository;
    private readonly SubjectsRepository _subjectsRepository;
    public GradesController(BaseRepository<Grade> baseRepository, ILogger<GradesController> logger, BaseRepository<Student> studentsRepository, BaseRepository<Subject> subjectsRepository) : base(baseRepository, logger)
    {
        _studentsRepository = (studentsRepository as StudentsRepository)!;
        _subjectsRepository = (subjectsRepository as SubjectsRepository)!;
    }
    
    public override async Task<IActionResult> Index()
    {
        var response = await _studentsRepository.Get();
        if (!response.Success)
            return View(new ServiceResponseModel<BaseIndexViewModel<Student>>()
            {
                Error = response.Error
            });
        return View(new ServiceResponseModel<BaseIndexViewModel<Student>>()
        {
            Success = true,
            Item = new BaseIndexViewModel<Student>()
            {
                Items = response.Item ?? new List<Student>()
            }
        });
    }
    
    [HttpGet("create")]
    public override async Task<IActionResult> Create()
    {
        var studentsResponse = await _studentsRepository.Get();
        var subjectsResponse = await _subjectsRepository.Get();
        
        return View(new GradeCreateViewModel()
        {
            Subjects = subjectsResponse.Item ?? new List<Subject>(),
            Students = studentsResponse.Item ?? new List<Student>()
        });
    }
    
    [HttpGet("get/{id:int}")]
    public override async Task<IActionResult> Get(int id)
    {
        var response = await BaseRepository.Get(id);
        var studentResponse = await _studentsRepository.Get(response.Item?.g_s_id ?? 0);
        if (studentResponse.Success)
            ViewBag.StudentName = studentResponse.Item?.s_full_name ?? "Нет имени";
        var subjectResponse = await _subjectsRepository.Get(response.Item?.g_sj_id ?? 0);
        if (subjectResponse.Success)
            ViewBag.SubjectName = subjectResponse.Item?.sj_name ?? "Нет названия";
        return View(response);
    }
}

ISRPO_LR1.Web/Controllers/StudentsController.cs
using ISRPO_LR1.Domain;
using ISRPO_LR1.Domain.Service;
using ISRPO_LR1.Web.Controllers.Base;
using ISRPO_LR1.Web.Models.ViewModels;
using ISRPO_LR1.Web.Repositories;
using ISRPO_LR1.Web.Repositories.Base;
using Microsoft.AspNetCore.Mvc;

namespace ISRPO_LR1.Web.Controllers;

[Route("students")]
public class StudentsController : BaseController<Student>
{
    public StudentsController(BaseRepository<Student> baseRepository, ILogger<StudentsController> logger) : base(baseRepository, logger)
    {
    }
}

ISRPO_LR1.Web/Controllers/SubjectsController.cs
using ISRPO_LR1.Domain;
using ISRPO_LR1.Web.Controllers.Base;
using ISRPO_LR1.Web.Repositories;
using ISRPO_LR1.Web.Repositories.Base;
using Microsoft.AspNetCore.Mvc;

namespace ISRPO_LR1.Web.Controllers;

[Route("subjects")]
public class SubjectsController : BaseController<Subject>
{
    public SubjectsController(BaseRepository<Subject> baseRepository, ILogger<SubjectsController> logger) : base(baseRepository, logger)
    {
    }
}

ISRPO_LR1.Web/Views/Grades/Create.cshtml
@using System.Globalization
@using ISRPO_LR1.Domain
@model ISRPO_LR1.Web.Models.ViewModels.GradeCreateViewModel
@{
    ViewBag.Title = "Создание оценки";
}

@using (Html.BeginForm("Create", "Grades", FormMethod.Post, new {@class = "form-horizontal d-flex flex-column w-100", id = "formData", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4 class="d-flex justify-content-center">
        @ViewBag.Title
    </h4>
    <hr/>
    @Html.ValidationSummary("", new {@class = "text-danger"})
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.g_value, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.DropDownListFor(u => u.g_value, new SelectList(new string[]
            {
                "1", "2", "3", "4", "5"
            }, new CultureInfo("ru-RU").TextInfo.ToTitleCase("Не выбрано")), new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.g_s, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.DropDownList("g_s_id", new SelectList(Model.Students ?? new List<Student>(), "s_id", "s_full_name"), new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.g_sj, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.DropDownList("g_sj_id", new SelectList(Model.Subjects ?? new List<Subject>(), "sj_id", "sj_name"), new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1 d-flex justify-content-center">
        <input id="submit" type="submit" class="btn btn-success w-100" value="Сохранить"/>
    </div>
}

ISRPO_LR1.Web/Views/Grades/Edit.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Domain.Grade>
@{
    ViewBag.Title = "Редактирование оценки";
}

@using (Html.BeginForm("Edit", "Grades", FormMethod.Post, new {@class = "form-horizontal d-flex flex-column w-100", id="formData", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4 class="d-flex justify-content-center">
        @ViewBag.Title
    </h4>
    <hr/>
    @Html.ValidationSummary("", new {@class = "text-danger"})
    @Html.Hidden("g_id", Model.Item.g_id)
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.Item.g_value, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextBox("g_value", Model.Item.g_value, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1 d-flex justify-content-center">
        <input id="submit" type="submit" class="btn btn-success w-100" value="Сохранить"/>
    </div>
}

ISRPO_LR1.Web/Views/Grades/Get.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Domain.Grade>
@{
    ViewBag.Title = "Оценка";
}

@if (Model.Success)
{
    <div class="media">
        <div class="media-body">
            <h5>Оценка: @Model.Item.g_value</h5>
            <h6>Студент: @ViewBag.StudentName</h6>
            <h6>Предмет: @ViewBag.SubjectName</h6>

            @if (ViewBag.IsEditable == true)
            {
                <div class="mb-1 d-flex justify-content-between w-100">
                    <a class="btn btn-success w-100 m-1" href="@Url.Action("Edit", "Grades", new {id = Model.Item.g_id})">Редактировать</a>
                    <a class="btn btn-danger w-100 m-1" href="@Url.Action("Delete", "Grades", new {id = Model.Item.g_id})">Удалить</a>
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="media">
        <h2>Произошла ошибка!</h2>
        <h5>@Model.Error</h5>
    </div>
}

ISRPO_LR1.Web/Views/Grades/Index.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Web.Models.ViewModels.BaseIndexViewModel<ISRPO_LR1.Domain.Student>>

<div class="panel-group">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="d-flex justify-content-center">
                @ViewBag.Title
            </h4>
            <hr/>
        </div>
        <div class="panel-body">
            @if (Model.Success)
            {
                @foreach (var student in Model.Item.Items)
                {
                    <div class="row">
                        <button class="btn btn-primary w-100 text-center" type="button" data-bs-toggle="collapse" data-bs-target=@("#courseCollapse" + student.s_id) aria-expanded="false" aria-controls=@("#courseCollapse" + student.s_id)>
                            Имя студента: @student.s_full_name
                        </button>
                        <div class="col mb-3">
                            <div class="collapse" data-bs-parent="#coursesParent" id=@("courseCollapse" + student.s_id)>
                                <div class="card card-body mb-3">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Оценка</th>
                                            <th scope="col">Предмет</th>
                                            <th scope="col">Действие</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @{
                                            var rowCounter = 1;
                                        }
                                        @foreach (var grade in student.Grades)
                                        {
                                            <tr>
                                                <th scope="row">@(rowCounter++)</th>
                                                <td>
                                                    <a href="@Url.Action("Get", "Grades", new {id = @grade.g_id})">@grade.g_value</a>
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("Get", "Subjects", new {id = @grade.g_sj_id})">@(grade.g_sj?.sj_name ?? "Без имени")</a>
                                                </td>
                                                <td>
                                                    <div class="mb-1 d-flex justify-content-between w-100">
                                                        <a class="btn btn-success w-100 m-1" href="@Url.Action("Edit", "Grades", new {id = grade.g_id, returnUrl = Context.Request.Path.Value,})">
                                                            <span class="mdi mdi-pencil-outline"></span>
                                                        </a>
                                                        <a class="btn btn-danger w-100 m-1" href="@Url.Action("Delete", "Grades", new {id = grade.g_id, returnUrl = Context.Request.Path.Value,})">
                                                            <span class="mdi mdi-trash-can-outline"></span>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <a class="btn btn-success w-100 m-1" href="@Url.Action("Create", "Grades", new {returnUrl = Context.Request.Path.Value,})">
                    <span class="mdi mdi-plus"></span>
                </a>
            }
            else
            {
                <div class="media">
                    <h2>Произошла ошибка!</h2>
                    <h5>@Model.Error</h5>
                </div>
            }
        </div>
    </div>
</div>

ISRPO_LR1.Web/Views/Shared/_Layout.cshtml
@using ISRPO_LR1.Web.Extensions
<!DOCTYPE html>
<html lang="ru" class="h-100">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewBag.Title - Университет</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/mdi/css/materialdesignicons.min.css" asp-append-version="true"/>
</head>
<body class="d-flex flex-column h-100">
<header class="header">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light text-light box-shadow">
        <div class="container-fluid">
            <a class="navbar-brand text-light mb-0 h1" asp-area="" asp-controller="Subjects" asp-action="Index">Предметы</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="@Html.IsSelected("Grades", "Index", "nav-item")">
                        <a class="nav-link text-light" href="@Url.Action("Index", "Grades")">Оценки</a>
                    </li>
                    <li class="@Html.IsSelected("Subjects", "Index", "nav-item")">
                        <a class="nav-link text-light" href="@Url.Action("Index", "Subjects")">Предметы</a>
                    </li>
                    <li class="@Html.IsSelected("Students", "Index", "nav-item")">
                        <a class="nav-link text-light" href="@Url.Action("Index", "Students")">Студенты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<main class="flex-shrink-0">
    <div class="container">
        @RenderBody()
    </div>
</main>

<footer class="footer mt-auto py-3">
    <div class="container text-center">
        <span class="text-muted">
            &copy; @DateTime.Now.Year - by ttlc
        </span>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ISRPO_LR1.Web/Views/Students/Create.cshtml
@model ISRPO_LR1.Domain.Student
@{
    ViewBag.Title = "Создание студента";
}

@using (Html.BeginForm("Create", "Students", FormMethod.Post, new {@class = "form-horizontal d-flex flex-column w-100", id="formData", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4 class="d-flex justify-content-center">
        @ViewBag.Title
    </h4>
    <hr/>
    @Html.ValidationSummary("", new {@class = "text-danger"})
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.s_email, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextBoxFor(m => m.s_email, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.s_birth_date, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextAreaFor(m => m.s_birth_date, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.s_full_name, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextAreaFor(m => m.s_full_name, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1 d-flex justify-content-center">
        <input id="submit" type="submit" class="btn btn-success w-100" value="Сохранить"/>
    </div>
}

ISRPO_LR1.Web/Views/Students/Edit.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Domain.Student>
@{
    ViewBag.Title = "Редактирование студента";
}

@using (Html.BeginForm("Edit", "Students", FormMethod.Post, new {@class = "form-horizontal d-flex flex-column w-100", id="formData", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4 class="d-flex justify-content-center">
        @ViewBag.Title
    </h4>
    <hr/>
    @Html.ValidationSummary("", new {@class = "text-danger"})
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.Item.s_email, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextBoxFor(m => m.Item.s_email, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.Item.s_birth_date, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextAreaFor(m => m.Item.s_birth_date, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.Item.s_full_name, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextAreaFor(m => m.Item.s_full_name, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1 d-flex justify-content-center">
        <input id="submit" type="submit" class="btn btn-success w-100" value="Сохранить"/>
    </div>
}

ISRPO_LR1.Web/Views/Students/Get.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Domain.Student>
@{
    ViewBag.Title = "Студент";
}

@if (Model.Success)
{
    <div class="media">
        <div class="media-body">
            <h5>Студент: @Model.Item.s_full_name</h5>
            <h6>Почта: @Model.Item.s_email</h6>
            <h6>Дата рождения: @Model.Item.s_birth_date</h6>

            @if (ViewBag.IsEditable == true)
            {
                <div class="mb-1 d-flex justify-content-between w-100">
                    <a class="btn btn-success w-100 m-1" href="@Url.Action("Edit", "Students", new {id = Model.Item.s_id})">Редактировать</a>
                    <a class="btn btn-danger w-100 m-1" href="@Url.Action("Delete", "Students", new {id = Model.Item.s_id})">Удалить</a>
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="media">
        <h2>Произошла ошибка!</h2>
        <h5>@Model.Error</h5>
    </div>
}

ISRPO_LR1.Web/Views/Students/Index.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Web.Models.ViewModels.BaseIndexViewModel<ISRPO_LR1.Domain.Student>>

<div class="panel-group">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="d-flex justify-content-center">
                @ViewBag.Title
            </h4>
            <hr/>
        </div>
        <div class="panel-body">
            @foreach (var student in Model.Item.Items)
            {
                <div class="row">
                    <button class="btn btn-primary w-100 text-center" type="button" data-bs-toggle="collapse" data-bs-target=@("#courseCollapse" + student.s_id) aria-expanded="false" aria-controls=@("#courseCollapse" + student.s_id)>
                        @student.s_full_name
                    </button>
                    <div class="col mb-3">
                        <div class="collapse" data-bs-parent="#coursesParent" id=@("courseCollapse" + student.s_id)>
                            <div class="card card-body mb-3">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Оценка</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @{
                                        var rowCounter = 1;
                                    }
                                    @foreach (var grade in student.Grades)
                                    {
                                        <tr>
                                            <th scope="row">@(rowCounter++)</th>
                                            <td>
                                                <a href="@Url.Action("Get", "Grades", new {id = @grade.g_id})">@grade.g_value</a>
                                            </td>
                                            <td>@(grade.g_value <= 0 ? "Не оценён" : grade.g_value)</td>
                                        </tr>
                                    }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

ISRPO_LR1.Web/Views/Subjects/Create.cshtml
@model ISRPO_LR1.Domain.Subject
@{
    ViewBag.Title = "Создание предмета";
}

@using (Html.BeginForm("Create", "Subjects", FormMethod.Post, new {@class = "form-horizontal d-flex flex-column w-100", id="formData", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4 class="d-flex justify-content-center">
        @ViewBag.Title
    </h4>
    <hr/>
    @Html.ValidationSummary("", new {@class = "text-danger"})
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.sj_name, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextBoxFor(m => m.sj_name, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.sj_hours, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextAreaFor(m => m.sj_hours, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1 d-flex justify-content-center">
        <input id="submit" type="submit" class="btn btn-success w-100" value="Сохранить"/>
    </div>
}

ISRPO_LR1.Web/Views/Subjects/Edit.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Domain.Subject>
@{
    ViewBag.Title = "Редактирование предмета";
}

@using (Html.BeginForm("Edit", "Subjects", FormMethod.Post, new {@class = "form-horizontal d-flex flex-column w-100", id="formData", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4 class="d-flex justify-content-center">
        @ViewBag.Title
    </h4>
    <hr/>
    @Html.ValidationSummary("", new {@class = "text-danger"})
    @Html.Hidden("sj_id", Model.Item.sj_id)
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.Item.sj_name, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextBox("sj_name", Model.Item.sj_name, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1">
        @Html.LabelFor(m => m.Item.sj_hours, new {@class = "col-md-2 form-label w-100"})
        <div class="col-md-10 w-100">
            @Html.TextBox("sj_hours", Model.Item.sj_hours, new {@class = "form-control w-100"})
        </div>
    </div>
    <div class="form-group mb-1 d-flex justify-content-center">
        <input id="submit" type="submit" class="btn btn-success w-100" value="Сохранить"/>
    </div>
}

ISRPO_LR1.Web/Views/Subjects/Get.cshtml
@model ISRPO_LR1.Domain.Service.ServiceResponseModel<ISRPO_LR1.Domain.Subject>
@{
    ViewBag.Title = "Предмет";
}

@if (Model.Success)
{
    <div class="media">
        <div class="media-body">
            <h5>Название: @Model.Item.sj_name</h5>
            <h6>Количество часов: @Model.Item.sj_hours</h6>

            @if (ViewBag.IsEditable == true)
            {
                <div class="mb-1 d-flex justify-content-between w-100">
                    <a class="btn btn-success w-100 m-1" href="@Url.Action("Edit", "Subjects", new {id = Model.Item.sj_id})">Редактировать</a>
                    <a class="btn btn-danger w-100 m-1" href="@Url.Action("Delete", "Subjects", new {id = Model.Item.sj_id})">Удалить</a>
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="media">
        <h2>Произошла ошибка!</h2>
        <h5>@Model.Error</h5>
    </div>
}